name: BasicInfo
version: ${project.version}
main: me.austinfrg.basicinfo.BasicInfo
api-version: 1.15
authors: [AustinFRG]
softdepend: [PlaceholderAPI]
description: A basic plugin that gives your players all the information they need.
commands:
  info:
    description: Sends all server links.
  website:
    description: Sends the server website link.
  forums:
    description: Sends the server forums link.
  discord:
    description: Sends the server Discord invite link.
  store:
    description: Sends the server store link.
  apply:
    description: Sends the server staff application link.
  appeal:
    description: Sends the server punishment appeal link.
  basicinfo:
    description: Sends a list of the commands with BasicInfo.
  basicreload:
    description: Reloads the BasicInfo config file.